[package]
name = "technopolis-be"
version = "0.1.0"
authors = ["silverscat-3 <silverscat_3@mail.sc3.fun>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
